compile_test:
  tags:
    - lotex2
  image: ruby:2.1
  variables:
    CI_DEBUG_TRACE: "true"
  script:
    - echo $CI_JOB_ID
    - echo "test" > artifact.txt
  artifacts:
    paths:
      - artifact.txt
