compile_test:
  tags:
    - ltx
  image: gitlab/gitlab-runner-helper
  variables:
    CI_DEBUG_TRACE: "true"
  script:
    - echo $CI_JOB_ID
    - echo "test" > artifact.txt
  artifacts:
    paths:
      - artifact.txt
